// AUTO-GENERATED by scripts/extract.mjs — do not edit by hand.
import homePage from './home.generated';
import aboutPage from './about.generated';
import papersPage from './papers.generated';
import beefPage from './beef.generated';
import porkPage from './pork.generated';
import chickenPage from './chicken.generated';
import greensPage from './greens.generated';
import sugarPage from './sugar.generated';
import newsPage from './news.generated';
import contactPage from './contact.generated';
import loginPage from './login.generated';
import notFoundPage from './notFound.generated';
import newsCmc2025Page from './newsCmc2025.generated';

export type PageModule = {
  title: string;
  metaDesc: string;
  bodyClass: string;
  headLinks: { rel?: string; href: string; type?: string; media?: string; as?: string; crossorigin?: string }[];
  headStyles: { id: string; css: string }[];
  bodyHtml: string;
};

export type RouteEntry = { slug: string; route: string; page: PageModule };

export const routes: RouteEntry[] = [
  { slug: "home", route: "/", page: homePage },
  { slug: "about", route: "/about-us", page: aboutPage },
  { slug: "papers", route: "/papers", page: papersPage },
  { slug: "beef", route: "/beef-tenderloin", page: beefPage },
  { slug: "pork", route: "/pork", page: porkPage },
  { slug: "chicken", route: "/chicken", page: chickenPage },
  { slug: "greens", route: "/greens", page: greensPage },
  { slug: "sugar", route: "/sugar", page: sugarPage },
  { slug: "news", route: "/news", page: newsPage },
  { slug: "contact", route: "/contact-us", page: contactPage },
  { slug: "login", route: "/login", page: loginPage },
  { slug: "notFound", route: "/404-error", page: notFoundPage },
  { slug: "newsCmc2025", route: "/valtoris-attends-canadian-meat-council-annual-conference-2025", page: newsCmc2025Page },
];

export const routeBySlug: Record<string, RouteEntry> = Object.fromEntries(routes.map(r => [r.slug, r]));
